apiVersion: federation/v1beta1
kind: Cluster
metadata:
  name: c1
spec:
  serverAddressByClientCIDRs:
  - clientCIDR: 0.0.0.0/0
    serverAddress: http://10.145.208.173:8080
  secretRef:
    name: c1-secret
